HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 29 Mar 2017 12:44:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 87100
Status: 200 OK
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4994
X-RateLimit-Reset: 1490794470
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding
ETag: "166e5b9784f0c53eb2e119373a38b330"
X-GitHub-Media-Type: github.machine-man-preview; format=json
Link: <https://api.github.com/organizations/4959742/repos?page=1>; rel="first", <https://api.github.com/organizations/4959742/repos?page=1>; rel="prev"
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Served-By: 52437fedc85beec8da3449496900fb9a
X-GitHub-Request-Id: 8181:1B3BB:43F5B0:55653B:58DBAC2F

[
  {
    "id": 54459620,
    "name": "procedures"
  },
  {
    "id": 54634039,
    "name": "sql-mock"
  }
]
