HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 29 Mar 2017 12:44:31 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 160910
Status: 200 OK
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4995
X-RateLimit-Reset: 1490794470
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding
ETag: "d2a348d0eda7395a301603b5c69802b8"
X-GitHub-Media-Type: github.machine-man-preview; format=json
ccess-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Served-By: 15bc4ab707db6d6b474783868c7cc828
X-GitHub-Request-Id: 8181:1B3BB:43F4DE:5564B2:58DBAC2F

[
  {
    "id": 12083245,
    "name": "scheduler"
  },
  {
    "id": 12896602,
    "name": "orderpad"
  }
]
