HTTP/1.1 200 OK
Server: GitHub.com
Date: Sun, 30 Apr 2017 20:59:13 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 167190
Status: 200 OK
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4990
X-RateLimit-Reset: 1493586167
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding
ETag: "48893eec72c2b2fa8fdf3549a4eeb97a"
X-GitHub-Media-Type: github.machine-man-preview; format=json
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Served-By: 7b641bda7ec2ca7cd9df72d2578baf75
X-GitHub-Request-Id: D3E4:1129:3C20C51:514DE6C:59065020

{
  "total_count": 2,
  "repositories": [
    {
      "id": 13444748,
      "name": "api",
      "full_name": "duncan3dc/test",
      "owner": {
        "login": "duncan3dc",
        "id": 4959742,
        "avatar_url": "https://avatars0.githubusercontent.com/u/4959742?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/duncan3dc",
        "html_url": "https://github.com/duncan3dc",
        "followers_url": "https://api.github.com/users/duncan3dc/followers",
        "following_url": "https://api.github.com/users/duncan3dc/following{/other_user}",
        "gists_url": "https://api.github.com/users/duncan3dc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/duncan3dc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/duncan3dc/subscriptions",
        "organizations_url": "https://api.github.com/users/duncan3dc/orgs",
        "repos_url": "https://api.github.com/users/duncan3dc/repos",
        "events_url": "https://api.github.com/users/duncan3dc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/duncan3dc/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "private": true,
      "html_url": "https://github.com/duncan3dc/api",
      "description": "Customer API to retrieve and send data from",
      "fork": false,
      "url": "https://api.github.com/repos/duncan3dc/api",
      "forks_url": "https://api.github.com/repos/duncan3dc/api/forks",
      "keys_url": "https://api.github.com/repos/duncan3dc/api/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/duncan3dc/api/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/duncan3dc/api/teams",
      "hooks_url": "https://api.github.com/repos/duncan3dc/api/hooks",
      "issue_events_url": "https://api.github.com/repos/duncan3dc/api/issues/events{/number}",
      "events_url": "https://api.github.com/repos/duncan3dc/api/events",
      "assignees_url": "https://api.github.com/repos/duncan3dc/api/assignees{/user}",
      "branches_url": "https://api.github.com/repos/duncan3dc/api/branches{/branch}",
      "tags_url": "https://api.github.com/repos/duncan3dc/api/tags",
      "blobs_url": "https://api.github.com/repos/duncan3dc/api/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/duncan3dc/api/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/duncan3dc/api/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/duncan3dc/api/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/duncan3dc/api/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/duncan3dc/api/languages",
      "stargazers_url": "https://api.github.com/repos/duncan3dc/api/stargazers",
      "contributors_url": "https://api.github.com/repos/duncan3dc/api/contributors",
      "subscribers_url": "https://api.github.com/repos/duncan3dc/api/subscribers",
      "subscription_url": "https://api.github.com/repos/duncan3dc/api/subscription",
      "commits_url": "https://api.github.com/repos/duncan3dc/api/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/duncan3dc/api/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/duncan3dc/api/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/duncan3dc/api/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/duncan3dc/api/contents/{+path}",
      "compare_url": "https://api.github.com/repos/duncan3dc/api/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/duncan3dc/api/merges",
      "archive_url": "https://api.github.com/repos/duncan3dc/api/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/duncan3dc/api/downloads",
      "issues_url": "https://api.github.com/repos/duncan3dc/api/issues{/number}",
      "pulls_url": "https://api.github.com/repos/duncan3dc/api/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/duncan3dc/api/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/duncan3dc/api/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/duncan3dc/api/labels{/name}",
      "releases_url": "https://api.github.com/repos/duncan3dc/api/releases{/id}",
      "deployments_url": "https://api.github.com/repos/duncan3dc/api/deployments",
      "created_at": "2013-10-09T14:38:26Z",
      "updated_at": "2014-10-26T22:13:34Z",
      "pushed_at": "2017-03-18T22:34:53Z",
      "git_url": "git://github.com/duncan3dc/api.git",
      "ssh_url": "git@github.com:duncan3dc/api.git",
      "clone_url": "https://github.com/duncan3dc/api.git",
      "svn_url": "https://github.com/duncan3dc/api",
      "homepage": null,
      "size": 41584,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "PHP",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 0,
      "mirror_url": null,
      "open_issues_count": 0,
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": false
      }
    },
    {
      "id": 22955805,
      "name": "aping",
      "full_name": "duncan3dc/aping",
      "owner": {
        "login": "duncan3dc",
        "id": 4959742,
        "avatar_url": "https://avatars0.githubusercontent.com/u/4959742?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/duncan3dc",
        "html_url": "https://github.com/duncan3dc",
        "followers_url": "https://api.github.com/users/duncan3dc/followers",
        "following_url": "https://api.github.com/users/duncan3dc/following{/other_user}",
        "gists_url": "https://api.github.com/users/duncan3dc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/duncan3dc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/duncan3dc/subscriptions",
        "organizations_url": "https://api.github.com/users/duncan3dc/orgs",
        "repos_url": "https://api.github.com/users/duncan3dc/repos",
        "events_url": "https://api.github.com/users/duncan3dc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/duncan3dc/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "private": true,
      "html_url": "https://github.com/duncan3dc/aping",
      "description": "Next generation of our API to retrieve and send data from",
      "fork": false,
      "url": "https://api.github.com/repos/duncan3dc/aping",
      "forks_url": "https://api.github.com/repos/duncan3dc/aping/forks",
      "keys_url": "https://api.github.com/repos/duncan3dc/aping/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/duncan3dc/aping/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/duncan3dc/aping/teams",
      "hooks_url": "https://api.github.com/repos/duncan3dc/aping/hooks",
      "issue_events_url": "https://api.github.com/repos/duncan3dc/aping/issues/events{/number}",
      "events_url": "https://api.github.com/repos/duncan3dc/aping/events",
      "assignees_url": "https://api.github.com/repos/duncan3dc/aping/assignees{/user}",
      "branches_url": "https://api.github.com/repos/duncan3dc/aping/branches{/branch}",
      "tags_url": "https://api.github.com/repos/duncan3dc/aping/tags",
      "blobs_url": "https://api.github.com/repos/duncan3dc/aping/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/duncan3dc/aping/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/duncan3dc/aping/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/duncan3dc/aping/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/duncan3dc/aping/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/duncan3dc/aping/languages",
      "stargazers_url": "https://api.github.com/repos/duncan3dc/aping/stargazers",
      "contributors_url": "https://api.github.com/repos/duncan3dc/aping/contributors",
      "subscribers_url": "https://api.github.com/repos/duncan3dc/aping/subscribers",
      "subscription_url": "https://api.github.com/repos/duncan3dc/aping/subscription",
      "commits_url": "https://api.github.com/repos/duncan3dc/aping/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/duncan3dc/aping/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/duncan3dc/aping/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/duncan3dc/aping/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/duncan3dc/aping/contents/{+path}",
      "compare_url": "https://api.github.com/repos/duncan3dc/aping/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/duncan3dc/aping/merges",
      "archive_url": "https://api.github.com/repos/duncan3dc/aping/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/duncan3dc/aping/downloads",
      "issues_url": "https://api.github.com/repos/duncan3dc/aping/issues{/number}",
      "pulls_url": "https://api.github.com/repos/duncan3dc/aping/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/duncan3dc/aping/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/duncan3dc/aping/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/duncan3dc/aping/labels{/name}",
      "releases_url": "https://api.github.com/repos/duncan3dc/aping/releases{/id}",
      "deployments_url": "https://api.github.com/repos/duncan3dc/aping/deployments",
      "created_at": "2014-08-14T14:00:45Z",
      "updated_at": "2015-03-22T15:03:06Z",
      "pushed_at": "2015-06-30T11:40:01Z",
      "git_url": "git://github.com/duncan3dc/aping.git",
      "ssh_url": "git@github.com:duncan3dc/aping.git",
      "clone_url": "https://github.com/duncan3dc/aping.git",
      "svn_url": "https://github.com/duncan3dc/aping",
      "homepage": null,
      "size": 228,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "PHP",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 0,
      "mirror_url": null,
      "open_issues_count": 1,
      "forks": 0,
      "open_issues": 1,
      "watchers": 0,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": false
      }
    }
  ]
}
